name: Register Flow using Github Storage 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: prefecthq/prefect:latest
    steps:
    # - uses: actions/checkout@v2
    # - uses: BSFishy/pip-action@v1
      # with:
        # requirements: requirements.txt
    - name: Authenticate to Prefect dependencies
      run: prefect cloud login -k ${{secrets.PREFECT_API_KEY}}
    - name: Register flow
      run: deploy
